# run: conda env create --file environment.yml
name: NSBEpi
channels:
  - conda-forge
  - bioconda
dependencies:
- python=3.9.15
- pip
- jupyter
- bedtools
- parallel  # FELIX
- pip:
  - pandas<3.0
  - openpyxl
  - umap-learn==0.5.4
  - scikit-learn==1.2.2
  - seaborn==0.12.2
  - scipy==1.9.3
  - plotly  # FELIX
  - combat  # FELIX
  - fastcluster  # FELIX (for faster seaborn's ClusterMap())
